In [1]:
mylist = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(mylist)

In [5]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0,5,7)

array([0.        , 0.83333333, 1.66666667, 2.5       , 3.33333333,
       4.16666667, 5.        ])

In [18]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [21]:
np.linspace(1,5,5)

array([1., 2., 3., 4., 5.])

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.55985621, 0.20083197, 0.12700406, 0.06535515, 0.21653254])

In [24]:
np.random.rand(5,4)

array([[0.92071453, 0.55152196, 0.22368134, 0.00161831],
       [0.40547394, 0.2412606 , 0.74426913, 0.79889472],
       [0.17966732, 0.99479298, 0.46517093, 0.98749985],
       [0.34828037, 0.67161339, 0.77963244, 0.48160084],
       [0.11880145, 0.8123642 , 0.27127717, 0.80888964]])

In [25]:
np.random.randn(4)

array([-0.22695502,  0.25406831,  1.7178093 ,  0.07788673])

In [26]:
np.random.randn(4,3)

array([[-0.34449356, -0.04708658,  1.41191113],
       [-0.06871747, -0.88280888, -0.32180618],
       [ 0.01538563, -0.27171471,  1.32993228],
       [ 0.07853984, -0.79472124,  1.82130702]])

In [31]:
np.random.randint(1,101,(5,5))

array([[74, 43, 74, 19, 21],
       [70, 18,  5, 81, 55],
       [37, 40, 89,  6, 13],
       [ 7, 56, 21, 16, 80],
       [83, 55, 62,  5,  6]])

In [34]:
arr = np.arange(25)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [36]:
ranarr = np.random.randint(0,50,10)

In [37]:
ranarr

array([28, 27,  7, 45, 22, 19, 28,  1, 28,  6])

In [38]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
arr.reshape(4,4)

ValueError: cannot reshape array of size 25 into shape (4,4)

In [41]:
ranarr

array([28, 27,  7, 45, 22, 19, 28,  1, 28,  6])

In [42]:
ranarr.max()

45

In [43]:
ranarr.min()

1

In [44]:
ranarr.argmax()

3

In [46]:
ranarr.argmin()

7

In [47]:
arr.shape

(25,)

In [48]:
arr = arr.reshape(5,5)

In [49]:
arr.shape

(5, 5)

In [50]:
arr.dtype

dtype('int32')

#Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [8]:
arr[0:5] = 100

In [9]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# note here how an operation on slice_of_arr object affects arr object

In [18]:
arr_copy = arr.copy()

In [19]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [20]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

# note here that using the copy method can solve this issue. Numpy saves memory by not copying completely new arrays each time a new variable is derived from it. Viewing a link to the original. Need to use .copy() to do this

In [24]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[0][0]

5

In [27]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[1][2]

30

In [32]:
arr_2d[0,1]

10

## can use both methods to grad particular values

In [34]:
 arr_2d[:,0]

array([ 5, 20, 35])

##  can grab columns like above

In [35]:
arr_2d[:,[0,2]]

array([[ 5, 15],
       [20, 30],
       [35, 45]])

## can pass in list of columns to return

In [36]:
arr = np.arange(1,11)

In [37]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
bool_arr = arr > 5

In [40]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [41]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr[arr < 3]

array([1, 2])

In [43]:
arr_2da = np.arange(50).reshape(5,10)

In [44]:
arr_2da

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [56]:
arr_2da[(arr_2da > 3) & (arr_2da < 42)]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
       21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41])

# Numpy Operations

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [60]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [62]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [63]:
1/0

ZeroDivisionError: division by zero

In [64]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [65]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [66]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [67]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [68]:
np.max(arr)

10

In [69]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [70]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])